version: "3.1"

services:
  db:
    container_name: pokemonDb
    image: mongo:latest
    restart: always
    volumes:
      - ./pokemonData:/data/db
    environment:
      - MONGO_INITDB_DATABASE= Pokemon
    ports:
      - 27017:27017
